[build]
builder = "nixpacks"

[deploy]
startCommand = "sh entrypoint.sh && concurrently \"npm run start\" \"node cron.js\""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[volumes]
data = "/app/data"

