[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'mkdir -p /app/data && chmod -R 755 /app/data && npm run start & node cron.js & wait'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[volumes]
data = "/app/data"
