[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'npm run start & npm run cron & wait'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[volumes]
data = "/app/data"
