[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'npm run db:migrate && npm run start & node cron.js & wait'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[volumes]
data = "/app/data"

