[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'chmod -R 755 /app/data 2>/dev/null || true && npm run start & node cron.js & wait'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[volumes]
data = "/app/data"
